// 요기요
### 네이버 주식 조회 API
GET localhost:8080/kospi/all

### 요기요 매장 정보 조회 API
# Parameters 사용
GET https://www.yogiyo.co.kr/api/v1/restaurants-geo/?category=치킨&items=5&lat=37.5027140&lng=127.092502&page=0
X-ApiSecret: fe5183cc3dea12bd0ce299cf110a75a2
x-Apikey: iphoneap


### 요기요 매장의 메뉴 조회
GET https://www.yogiyo.co.kr/api/v1/restaurants/313580/menu/
X-ApiSecret: fe5183cc3dea12bd0ce299cf110a75a2
x-Apikey: iphoneap


### 모든 카테고리 요기요 매장 정보 조회 API
GET https://www.yogiyo.co.kr/api/v1/restaurants-geo/?lat=37.54775437002297&lng=127.06083008344&page=0&items=20
X-ApiSecret: fe5183cc3dea12bd0ce299cf110a75a2
x-Apikey: iphoneap

// 배달의 민족
### 배민 사용자 조회 API
GET https://location-api.baemin.com/v1/addresses/current?adid=8187CDE8-4C55-47B0-BAB0-2669BB3FF747&appver=11.26.1&carrier=&deviceModel=iPhone7%2C2&dvc_uniq_id=D8526444-59E1-4610-A277-0557E420A0D6&dvcid=OPUD01BCCF1C-8E8F-47CA-B891-BC50A2F274C4&memberNo=000000000000&oscd=1&osver=12.400000&sessionid=3dde886418b8764005f9a7dfaa736161&site=7jWXRELC2e HTTP/1.1
Host: location-api.baemin.com
Accept-Encoding: br, gzip, deflate
Cookie: __cf_bm=JMMH5nzT5G54LO3NBf4k86YWWTTeE0CK4gkgarAKUww-1657632803-0-AW7hJGuC6Pw3nB/JaEkTTrvLMXuvqxH+Tbe8Jryi3hlBQEcViszL+bQ3b4hxr3ji1oye+rWVrGEYiqEgGN7KeB/sQXN+J5V/EYWzY23eX0sj
Connection: keep-alive
Accept: */*
Carrier:
User-Agent: iph1_11.26.1
Authorization: Bearer guest
Accept-Language: ko-kr
USER-BAEDAL: LVtTvgJXl2UgjbU/AmqoAmVIC4dZgbT33ods0fRIJOtUO0716WYdQYdxyzca1BgITliCsm1dw1+QIUJaP0KYQfK7DpZ+ebzoieyxFgK02OCEpQbnWRttWII0x5H87sWYnCdtpZ3nZVolXxyFHk8m6KP1L2Y4uo6bax4c+5m3zAaIyj+YU/xdeRAvluN+ZHl5ChOIXkq8mDTgxEzLqvAUpzezgJC/rwdnjb2bCAh0q9g=

### 68. 배민 사용자 조회 API
// dvcid : 사용자 디바이스 ID // memberNo : 사용자 ID ( 비회원: 000000000000 )
GET https://location-api.baemin.com/v1/addresses/current?dvcid=OPUD01BCCF1C-8E8F-47CA-B891-BC50A2F274C4&memberNo=000000000000
Authorization: Bearer guest
User-Agent: iph1_11.26.1

### 85. 배민 주문 정렬 기준 조회 API
GET https://shopdp-api.baemin.com/display-groups/BAEMIN_DELIVERY_HOME?adid=8187CDE8-4C55-47B0-BAB0-2669BB3FF747&appver=11.26.1&carrier=&deviceModel=iPhone7%2C2&dvc_uniq_id=D8526444-59E1-4610-A277-0557E420A0D6&dvcid=OPUD01BCCF1C-8E8F-47CA-B891-BC50A2F274C4&latitude=37.54766676253973&longitude=127.0609096938018&oscd=1&osver=12.400000&sessionid=3dde886418b8764005f9a7dfaa736161&site=7jWXRELC2e HTTP/1.1
Host: shopdp-api.baemin.com
Cookie: __cf_bm=JMMH5nzT5G54LO3NBf4k86YWWTTeE0CK4gkgarAKUww-1657632803-0-AW7hJGuC6Pw3nB/JaEkTTrvLMXuvqxH+Tbe8Jryi3hlBQEcViszL+bQ3b4hxr3ji1oye+rWVrGEYiqEgGN7KeB/sQXN+J5V/EYWzY23eX0sj
Connection: keep-alive
Accept: */*
Carrier:
User-Agent: iph1_11.26.1
Accept-Language: ko-kr
Accept-Encoding: br, gzip, deflate
USER-BAEDAL: LVtTvgJXl2UgjbU/AmqoAmVIC4dZgbT33ods0fRIJOtUO0716WYdQYdxyzca1BgITliCsm1dw1+QIUJaP0KYQfK7DpZ+ebzoieyxFgK02OCEpQbnWRttWII0x5H87sWYnCdtpZ3nZVolXxyFHk8m6KP1L2Y4uo6bax4c+5m3zAaIyj+YU/xdeRAvluN+ZHl5ChOIXkq8mDTgxEzLqvAUpzezgJC/rwdnjb2bCAh0q9g=

### 91. 배민 카테고리 별 주문 가능 점포 조회(점포 개수 제한?)
GET https://shopdp-api.baemin.com/v1/BAEMIN/curations?displayCategory=CHICKEN&latitude=37.54766676253973&longitude=127.0609096938018
Host: shopdp-api.baemin.com
User-Agent: iph1_11.26.1
USER-BAEDAL: LVtTvgJXl2UgjbU/AmqoAmVIC4dZgbT33ods0fRIJOtUO0716WYdQYdxyzca1BgITliCsm1dw1+QIUJaP0KYQfK7DpZ+ebzoieyxFgK02OCEpQbnWRttWII0x5H87sWYnCdtpZ3nZVolXxyFHk8m6KP1L2Y4uo6bax4c+5m3zAaIyj+YU/xdeRAvluN+ZHl5ChOIXkq8mDTgxEzLqvAUpzezgJC/rwdnjb2bCAh0q9g=

### 91. 배민 카테고리 별 주문 가능 점포 조회
// displayCategory: 카테고리 // latitude: 위도, longitude: 경도 // distance: 거리 구분 // sort
GET https://shopdp-api.baemin.com/v1/BAEMIN/curations?displayCategory=CHICKEN&latitude=37.54766676253973&longitude=127.0609096938018&sort=SORT__DISTANCE&distance=
Host: shopdp-api.baemin.com
User-Agent: iph1_11.26.1

### 369. 배민 매장 메뉴 조회
// PathVarialbe: 매장 번호(ex:10724672) // lat: 위도, lng: 경도
GET https://shopdp-api.baemin.com/v8/shop/10724672/detail?lat=37.54766676253973&lng=127.0609096938018
Host: shopdp-api.baemin.com
User-Agent: iph1_11.26.1

### 배민 매장 검색으로 조회 API
GET https://search-gateway.baemin.com/v1/search?appver=11.26.1&baeminDeliveryFilter=&baeminDeliverySort=SORT__DEFAULT&currentTab=BAEMIN_DELIVERY&dvcid=OPUD01BCCF1C-8E8F-47CA-B891-BC50A2F274C4&isBmartRegion=1&isFirstRequest=1&keyword=bbq&latitude=37.54766676253973&limit=25&longitude=127.0609096938018
User-Agent: iph1_11.26.1
USER-BAEDAL: LVtTvgJXl2UgjbU